---
- name: Installing additional software
  apt:
    name: "{{ software_packages }}"
    state: present

- name: Adding "{{ user_name }}"" to multiple groups
  user:
    name: "{{ user_name }}"
    groups: libvirt,libvirt-qemu
    append: yes