---
- hosts: all
  become: true
  become_user: root
  become_method: su

  vars_files:
    - vars/main.yml
    - vars/nonfree.yml
    - vars/mirror.yml
    - vars/xorg.yml
    - vars/gpu.yml
    - vars/xfce.yml
    - vars/packages.yml
    - vars/libvirt.yml
    - vars/lxc.yml
    - vars/emulator.yml
    - vars/wine.yml
    - vars/steam.yml
    - vars/ansible.yml
    - vars/docker.yml

  handlers:
    - name: Include handlers
      import_tasks: tasks/handlers.yml

  tasks:
    - import_tasks: tasks/main.yml
      when: ansible_distribution == 'Debian'
