---
- hosts: all
  become: true
  become_user: root
  become_method: su

  vars_files:
    - vars/main.yml
    - vars/mirror.yml
    - vars/xorg.yml
    - vars/gnome.yml
    - vars/xfce.yml
    - vars/packages.yml

  handlers:
    - name: Include handlers
      import_tasks: tasks/handlers.yml

  tasks:
    - import_tasks: tasks/main.yml
      when: ansible_distribution == 'Debian'
