---
- hosts: all
  become: true
  become_user: root
  become_method: su

  roles:
    ##
    # Basic things
    ##
    - apt
    - update
    - vim_alternative
    - dotfiles
    - postfix
    - rsyslog
    - ssh
    - sudo
    - pam
    - groups
    - ntp
    - sysctl
    - grub
    - fstrim
    - fail2ban
    
    ##
    # Desktop related
    ##
    - xorg
    - xfce
    - gnome
    - software
    - fontconfig

    ##
    # Gaming
    ##
    - gaming

    ##
    # Additional apps
    ##
    - virtualbox
    - vscode
    - rpi_imager
    - ansible
    - vagrant
    - salt
    - docker
    - discord

    ##
    # Reboot system
    ##
    - reboot
