---
- hosts: all
  become: true
  become_user: root
  become_method: su

  roles:
    ##
    # Basic setup
    ##
    - apt
    - update
    - vim_alternative
    - dotfiles
    - postfix
    - rsyslog
    - ssh
    - sudo
    - pam
    - groups
    - ntp
    - sysctl
    - grub
    - fstrim
    - fail2ban
    
    ##
    # Desktop related packages
    ##
    - xorg
    - xfce
    - software
    - fontconfig

    ##
    # Additional packages
    ##
    - additional_software

    ##
    # Virtualization packages
    ##
    - virt

    ##
    # Gaming
    ##
    - gaming

    ##
    # External packages
    ##
    - vscode
    - ansible
    - salt
    - docker
    - discord

    ##
    # Rebooting the system
    ##
    - reboot
