---
- name: Installing wget
  apt:
    name: wget
    state: present

- name: Add Element key
  shell: wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg

- name: Adding Element repository
  copy:
    src: files/element/element.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: '0644'
  notify: update apt cache

- name: Update APT cache
  meta: flush_handlers

- name: Installing Element
  apt:
    name: element-desktop
    state: present

