---
- name: Setup hinting (Slight)
  file:
    src: "/usr/share/fontconfig/conf.avail/10-hinting-slight.conf"
    dest: "/etc/fonts/conf.d/10-hinting-slight.conf"
    state: link

- name: Setup sub pixel (RGB)
  file:
    src: "/usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf"
    dest: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf"
    state: link

- name: Deploy Kubuntu Color Emoji configs (Emoji Fix)
  copy:
    src: files/fontconfig/50-user.conf
    dest: "/etc/fonts/conf.d/50-user.conf"
    owner: root
    group: root
    mode: '0644'

- name: Deploy Kubuntu Color Emoji configs (Emoji fix)
  copy:
    src: files/fontconfig/56-kubuntu-noto.conf
    dest: "/etc/fonts/conf.d/56-kubuntu-noto.conf"
    owner: root
    group: root
    mode: '0644'