---
- name: Check if JDownloader 2 setup already exist
  stat: path=/home/{{ user_name }}/JD2SilentSetup_x64.sh
  register: jdownloader

- name: Downloading JDownloader 2 Setup
  ansible.builtin.command: "wget 'http://installer.jdownloader.org/JD2SilentSetup_x64.sh' -O /home/{{ user_name }}/JD2SilentSetup_x64.sh"
  become: true
  become_user: "{{ user_name }}"
  become_method: su
  when: not jdownloader.stat.exists

- name: Change permission in the JDownloader setup script
  ansible.builtin.file:
    path: /home/{{ user_name }}/JD2SilentSetup_x64.sh
    owner: "{{ user_name }}"
    mode: '0770'
  become: true
  become_user: "{{ user_name }}"
  become_method: su
  when: not jdownloader.stat.exists