---
- import_tasks: tasks/apt.yml
  tags: apt

- import_tasks: tasks/upgrade.yml
  tags: upgrade

- import_tasks: tasks/vim.yml
  tags: vim

- import_tasks: tasks/dotfiles.yml
  tags: dotfiles

- import_tasks: tasks/postfix.yml
  tags: postfix

- import_tasks: tasks/sshd.yml
  tags: sshd

- import_tasks: tasks/sudo.yml
  tags: sudo

- import_tasks: tasks/doas.yml
  tags: doas

- import_tasks: tasks/ntp.yml
  tags: ntp

- import_tasks: tasks/sysctl.yml
  tags: sysctl

- import_tasks: tasks/grub.yml
  tags: grub

- import_tasks: tasks/fstrim.yml
  tags: fstrim

- import_tasks: tasks/fail2ban.yml
  tags: fail2ban

- import_tasks: tasks/xorg.yml
  tags: xorg

- import_tasks: tasks/xfce.yml
  tags: xfce
  when: use_xfce

- import_tasks: tasks/kde.yml
  tags: kde
  when: use_kde

- import_tasks: tasks/gnome.yml
  tags: gnome
  when: use_kde

- import_tasks: tasks/packages.yml
  tags: packages

- import_tasks: tasks/groups.yml
  tags: groups

- import_tasks: tasks/fontconfig.yml
  tags: fontconfig

- import_tasks: tasks/fonts.yml
  tags: fonts

- import_tasks: tasks/virt.yml
  tags: virt
  when: use_kvm

- import_tasks: tasks/virtualbox.yml
  tags: virtualbox
  when: use_vbox

- import_tasks: tasks/brave.yml
  tags: brave
  when: external

- import_tasks: tasks/gaming.yml
  tags: gaming
  when: gaming

- import_tasks: tasks/mullvad.yml
  tags: mullvad
  when: external

- import_tasks: tasks/powershell.yml
  tags: powershell
  when: external

- import_tasks: tasks/vscode.yml
  tags: vscode
  when: external

- import_tasks: tasks/flatpak.yml
  tags: flatpak
  when: flatpak

- import_tasks: tasks/liquorix.yml
  tags: liquorix
  when: use_liquorix

- import_tasks: tasks/xanmod.yml
  tags: xanmod
  when: use_xanmod

- import_tasks: tasks/pipx.yml
  tags: pipx

- import_tasks: tasks/veracrypt.yml
  tags: veracrypt
  when: external

- import_tasks: tasks/docker.yml
  tags: docker

- import_tasks: tasks/firewall.yml
  tags: firewall
  when: use_firewall

- import_tasks: tasks/reboot.yml
  tags: reboot
  when: reboot
