---
- import_tasks: tasks/apt.yml
  tags: apt

- import_tasks: tasks/upgrade.yml
  tags: upgrade

- import_tasks: tasks/vim.yml
  tags: vim

- import_tasks: tasks/dotfiles.yml
  tags: dotfiles

- import_tasks: tasks/postfix.yml
  tags: postfix

- import_tasks: tasks/sshd.yml
  tags: sshd

- import_tasks: tasks/sudo.yml
  tags: sudo

- import_tasks: tasks/ntp.yml
  tags: ntp

- import_tasks: tasks/sysctl.yml
  tags: sysctl

- import_tasks: tasks/grub.yml
  tags: grub

- import_tasks: tasks/fstrim.yml
  tags: fstrim

- import_tasks: tasks/fail2ban.yml
  tags: fail2ban

- import_tasks: tasks/xorg.yml
  tags: xorg

- import_tasks: tasks/gnome.yml
  tags: gnome
  when: gnome_desktop

- import_tasks: tasks/xfce.yml
  tags: xfce
  when: xfce_desktop

- import_tasks: tasks/kde.yml
  tags: kde
  when: kde_desktop

- import_tasks: tasks/packages.yml
  tags: packages

- import_tasks: tasks/groups.yml
  tags: groups

- import_tasks: tasks/fontconfig.yml
  tags: fontconfig

- import_tasks: tasks/virt.yml
  tags: virt

- import_tasks: tasks/vscodium.yml
  tags: vscodium

- import_tasks: tasks/discord.yml
  tags: discord

- import_tasks: tasks/virtualbox.yml
  tags: virtualbox

- import_tasks: tasks/element.yml
  tags: element

- import_tasks: tasks/brave.yml
  tags: brave

- import_tasks: tasks/gaming.yml
  tags: gaming

- import_tasks: tasks/signal.yml
  tags: signal

- import_tasks: tasks/mullvad.yml
  tags: mullvad

- import_tasks: tasks/powershell.yml
  tags: powershell

- import_tasks: tasks/reboot.yml
  tags: reboot
