---
- name: Downloading Mullvad Client
  shell: wget 'https://mullvad.net/en/download/app/deb/latest' -O /tmp/mullvad.deb

- name: Installing Mullvad Client
  ansible.builtin.apt:
    deb: /tmp/mullvad.deb

- name: Remove Mullvad Client .deb package
  ansible.builtin.file:
    path: /tmp/mullvad.deb
    state: absent