---
- name: Downloading PowerShell
  shell: wget 'https://github.com/PowerShell/PowerShell/releases/download/v7.4.5/powershell_7.4.5-1.deb_amd64.deb' -O /tmp/powershell.deb

- name: Installing PowerShell
  ansible.builtin.apt:
    deb: /tmp/powershell.deb

- name: Remove PowerShell .deb package
  ansible.builtin.file:
    path: /tmp/powershell.deb
    state: absent
