---
- name: Downloading Raspberry Pi Imager
  shell: wget 'https://downloads.raspberrypi.org/imager/imager_latest_amd64.deb' -O /tmp/rpi-imager.deb

- name: Installing Raspberry Pi Imager
  ansible.builtin.apt:
    deb: /tmp/rpi-imager.deb

- name: Remove Raspberry Pi Imager .deb package
  ansible.builtin.file:
    path: /tmp/rpi-imager.deb
    state: absent