---
- name: Downloading VeraCrypt
  shell: wget 'https://launchpad.net/veracrypt/trunk/1.26.14/+download/veracrypt-1.26.14-Debian-12-amd64.deb' -O /tmp/veracrypt.deb

- name: Installing VeraCrypt
  ansible.builtin.apt:
    deb: /tmp/veracrypt.deb

- name: Removing VeraCrypt .deb package
  ansible.builtin.file:
    path: /tmp/veracrypt.deb
    state: absent