---
- name: Installing wget
  apt:
    name: wget
    state: present

- name: Add Virtualbox key
  shell: wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg

- name: Adding Virtualbox repository
  copy:
    src: files/virtualbox/vbox.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: '0644'
  notify: update apt cache

- name: Update APT cache
  meta: flush_handlers

- name: Installing Virtualbox
  apt:
    name: virtualbox-7.1
    state: present

- name: Adding "{{ user_name }}" to vboxusers group
  user:
    name: "{{ user_name }}"
    groups: vboxusers
    append: yes