---
- name: Installing wget
  apt:
    name: wget
    state: present

- name: Add XanMod key
  shell: wget -qO - https://dl.xanmod.org/archive.key | gpg --batch --yes --dearmor -vo /usr/share/keyrings/xanmod-archive-keyring.gpg

- name: Adding XanMod repository
  copy:
    src: files/xanmod/xanmod.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: '0644'
  notify: update apt cache

- name: Update APT cache
  meta: flush_handlers

- name: Installing XanMod LTS kernel
  apt:
    name: linux-xanmod-lts-x64v3
    state: present
