---
- name: Add Vagrant key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Vagrant repository
  copy:
    src: vagrant.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: '0644'

- name: Update package cache
  apt:
    update_cache: yes

- name: Installing Vagrant
  apt:
    name: "{{ vagrant_package }}"
    state: present