---
- name: (Postfix) Setup debconf
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: Local only
    vtype: select

- name: (Postfix) Install packages
  apt: 
    name: postfix
    state: present

- name: (Postfix) Changing banner
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtpd_banner'
    line: 'smtpd_banner = $myhostname ESMTP'

- name: (Postfix) Setup Postfix aliases
  lineinfile:
    path: /etc/aliases
    line: "root: {{ user_name }}"

- name: Running newaliases
  shell: newaliases

- name: Restart Postfix
  systemd:
    name: postfix
    state: restarted

- name: Installing MUA
  apt: 
    name: bsd-mailx 
    state: present

- name: (Mail) Send welcome mail
  shell: echo "Postfix ready" | mail -s Postfix "{{ user_name }}"
