#!/usr/sbin/nft -f
flush ruleset
table inet filter {
    chain input {
        type filter hook input priority 0;
        meta iif lo accept;
        tcp dport 22 accept;
        ct state related,established accept;
        reject with icmp type port-unreachable;;
    }
    chain forward {
        type filter hook forward priority 0;
        policy drop;
    }
    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}
