gaming_packages:
  - mupen64plus-ui-console
  - mednafen
  - dosbox
  - aisleriot
  - wine
  - wine32
  - wine64
  - libwine
  - libwine:i386
  - fonts-wine
  - winetricks
  - steam
  - libglx-mesa0:i386
  - mesa-vulkan-drivers
  - mesa-vulkan-drivers:i386
  - libgl1-mesa-dri:i386
  - zsnes:i386
