- name: Installing iptables
  apt:
    name: iptables
    state: present

- name: Copying firewall script
  copy:
    src: fw.sh
    dest: /etc/
    owner: root
    group: root
    mode: 0740

- name: Applying firewall rules
  shell: /etc/fw.sh

- name: (iptables-persistent) Setup debconf (1/2)
  debconf:
    name: iptables-persistent
    question: iptables-persistent/autosave_v4
    value: 'true'
    vtype: select

- name: (iptables-persistent) Setup debconf (2/2)
  debconf:
    name: iptables-persistent
    question: iptables-persistent/autosave_v6
    value: 'false'
    vtype: select

- name: Installing iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Saving iptables rules (IPv4)
  shell: iptables-save > /etc/iptables/rules.v4