---
- name: Install virtualization related packages
  apt:
    name: "{{ virt_packages }}"
    state: present

- name: Adding "{{ user_name }}" to libvirt group
  user:
    name: "{{ user_name }}"
    groups: libvirt
    append: yes