---
- name: Configuring PAM (common-auth)
  copy: 
    src: common-auth
    dest: /etc/pam.d/
    owner: root
    group: root
    mode: '0644'

- name: Configuring PAM (login)
  copy: 
    src: login
    dest: /etc/pam.d/
    owner: root
    group: root
    mode: '0644'

- name: Configuring PAM (sshd)
  copy: 
    src: sshd
    dest: /etc/pam.d/
    owner: root
    group: root
    mode: '0644'

- name: Installing pwquality
  apt:
    name: "{{ pam_packages }}"
    state: present