---
- name: Add Virtualbox key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Add Virtualbox repository
  copy:
    src: vbox.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: '0644'

- name: Update package cache
  apt:
    update_cache: yes

- name: Install Virtualbox
  apt:
    name: "{{ vbox_package }}"
    state: present

- name: Add user "{{ user_name }}" to group vboxusers
  user:
    name: "{{ user_name }}"
    groups: vboxusers
    append: yes

