- name: Add VirtualBox key
  shell: wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg

- name: Adding VirtualBox repository
  copy:
    src: virtualbox.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: '0644'

- name: Update package cache
  apt:
    update_cache: yes

- name: Installing VirtualBox
  apt:
    name: "{{ virtualbox_package }}"
    state: present

- name: Add user "{{ user_name }}" to group vboxusers
  user:
    name: "{{ user_name }}"
    groups: vboxusers
    append: yes