---
- name: Add Ansible key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367

- name: Add Ansible repository
  copy:
    src: ansible.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: '0644'

- name: Update package cache
  apt:
    update_cache: yes

- name: Installing Ansible
  apt:
    name: "{{ ansible_package }}"
    state: present