---
- name: Setting up firewall (nftables)
  copy:
    src: nftables.conf
    dest: /etc
    owner: root
    group: root
    mode: '0644'

- name: Enabling firewall
  systemd:
    name: nftables
    enabled: yes

- name: Start firewall
  systemd:
    state: started
    name: nftables
