---
- name: Add custom GRUB config
  copy: 
    src: grub
    dest: /etc/default/
    owner: root
    group: root
    mode: '0644'

- name: Disable Debian GRUB theme
  file:
    path: /etc/grub.d/05_debian_theme
    owner: root
    group: root
    mode: '0644'

- name: Update GRUB configuration
  shell: update-grub2
