---
- name: Add custom grub config
  copy: 
    src: grub
    dest: /etc/default/
    owner: root
    group: root
    mode: '0644'

- name: Changing grub theme
  file:
    path: /etc/grub.d/05_debian_theme
    owner: root
    group: root
    mode: '0644'

- name: Update Grub
  shell: update-grub2
